# Generated by Django 3.1 on 2021-03-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201118_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wecom_id',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
    ]
